### ISSUE TITLE
yolo

### ISSUE THREAD

**Issue by musicleaf** [hqy1433/Lalalalalala#1]
请问这个模型是yolo第几代的？能在现在新出的MaixCAM上跑吗？

**Comment by hqy1433** [comment]
你好，这个模型是给maixbit用的，默认是yolov2，目前maixcan上跑不了，有时间我转一份出来

**Comment by hqy1433** [comment]
你好,现在你可以在https://maixhub.com/model/zoo/434下载以供MaixCam使用的模型
